version: "2.4"
services:
  mockServer:
    image: mockserver/mockserver:latest
    ports:
      - 1080:1080
    environment:
      LOG_LEVEL: "DEBUG"
      MOCKSERVER_PROPERTY_FILE: /config/mockserver.properties
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
      MOCKSERVER_WATCH_INITIALIZATION_JSON: "true"
    volumes:
      - type: bind
        source: .
        target: /config
